package ybsDirectory;

import Exception.SpecialCharacterException;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import java.util.StringTokenizer;

import Exception.liscenseException;
/**
 *
 * @author ICE
 */
public class DriverDetail extends javax.swing.JFrame {
    int count=0;
    private Connection con=null;
    public String id;
    private Statement ste=null;
    private ResultSet rs=null;
    private String query;
    DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
    Date date=new Date();
    
    private User user=new User();

    public DriverDetail() {
        initComponents();
        con=new DBConnection().getDBConnection();
        jDateChooser1.setDate(date);
        jDateChooser1.getJCalendar().setMinSelectableDate(date);
        addCboDriverName(CboDriverName);
        addCboBusLine(CboBusLineNo);
        
    }
    
    public DriverDetail(User user) {
    	initComponents();
        con=new DBConnection().getDBConnection();
        jDateChooser1.setDate(date);
        jDateChooser1.getJCalendar().setMinSelectableDate(date);
        addCboDriverName(CboDriverName);
        addCboBusLine(CboBusLineNo);
                	    		   
    	this.user.setUserName(user.getUserName());
    	this.user.setType(user.getType());                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CboDriverName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ErrorlblDate = new javax.swing.JLabel();
        Errorlblname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CboBusLineNo = new javax.swing.JComboBox<>();
        ErrorlblBusLine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLisence = new javax.swing.JTextField();
        ErrorlblLicense = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Driver Detail");

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ybsDirectory/userProfile.png"))); // NOI18N

        jLabel3.setText("Name:");

        CboDriverName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        CboDriverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboDriverNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Date:");

        jPanel4.setBackground(new java.awt.Color(169, 217, 131));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ybsDirectory/myanmar-random-set-vector-yangon-450w-1072532099~2.jpg"))); // NOI18N

        jLabel2.setText("Bus Line No:");

        CboBusLineNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Item 2", "Item 3", "Item 4" }));
        CboBusLineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboBusLineNoActionPerformed(evt);
            }
        });

        jLabel6.setText("License Plate No:");

        txtLisence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLisenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(CboBusLineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLisence, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorlblLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrorlblBusLine, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CboBusLineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorlblBusLine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLisence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorlblLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btCancel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ErrorlblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(Errorlblname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CboDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CboDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Errorlblname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ErrorlblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ybsDirectory/back.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboBusLineNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboBusLineNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboBusLineNoActionPerformed

    private void txtLisenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLisenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLisenceActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        id=getAutoID("BusDriverDetailID","busdriverdetail","BDD");
        boolean cond=true;
        try{
            if(CboDriverName.getSelectedIndex()==0){
                Errorlblname.setForeground(new java.awt.Color(255, 0, 0));
    		Errorlblname.setText("*Please Choose Driver Name.");
                cond=false;
            }  
            else if(CboBusLineNo.getSelectedIndex()==0){
                ErrorlblBusLine.setForeground(new java.awt.Color(255, 0, 0));
                ErrorlblBusLine.setText("*Please Choose Bus Line.");
                cond=false;
            }
            else if(txtLisence.getText().trim().isEmpty()){
                
                ErrorlblLicense.setForeground(new java.awt.Color(255, 0, 0));
                ErrorlblLicense.setText("*Please Enter License.");
                txtLisence.requestFocus();
                cond=false;
            }
                
            else if(!(txtLisence.getText().trim().isEmpty())){
                String l=txtLisence.getText().toString().trim();
                StringTokenizer st=new StringTokenizer(l,"/");                                
                
                if(st.countTokens()==1){
                    throw new liscenseException();
                }
                //System.out.print(count);
                else {
                    
                    Pattern pattern=Pattern.compile("[a-zA-Z0-9/]+$");
                    Matcher matcher=pattern.matcher(txtLisence.getText().trim());
                        if(!matcher.find()) {
                            cond=false;
                           throw new SpecialCharacterException();
                        }
                }
            }
            else{
                cond=true;
            }
            if(cond){
                String Did=null;
                ste=con.createStatement();
                String query="SELECT BusDriverID FROM busdriver WHERE BusDriverName ='" + CboDriverName.getSelectedItem().toString()  + "'";
                rs=ste.executeQuery(query); 
                if(rs.next()){
                     Did=rs.getString(1);
                }
                query= "insert into busdriverdetail(BusDriverDetailID,BusLineNo,BusDriverID,Plate,Date) values ('"+id+"','"+CboBusLineNo.getSelectedItem().toString()+"','"+Did+"','"+txtLisence.getText().toString()+"','"+dateformat.format(jDateChooser1.getDate())+"')";
                int result=ste.executeUpdate(query);
                if(result==1){
                    clearData();
                    JOptionPane.showMessageDialog(this,"This User record is save successfully.");
                    
                  //update detail in update detail table    				
    				addUpdateDetail("added bus info for license plate : " + txtLisence.getText().toString().trim());
                }
            }
            
        }catch(liscenseException e){
            ErrorlblLicense.setForeground(new java.awt.Color(255, 0, 0));
            txtLisence.requestFocus();
            txtLisence.setText("");
            ErrorlblLicense.setText(e.getMessage());
            }
        catch(SpecialCharacterException e){
            ErrorlblLicense.setForeground(new java.awt.Color(255, 0, 0));
            txtLisence.requestFocus();
            txtLisence.setText("");
            ErrorlblLicense.setText(e.getMessage());
           }
        catch(Exception e){
            System.out.print(e);
            System.out.println(id);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void CboDriverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboDriverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboDriverNameActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.setVisible(false);
        new MainMenu(user).setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverDetail().setVisible(true);
            }
        });
    }
    
    private void addCboDriverName(JComboBox cboBox) {
        boolean cond=true;
    	cboBox.removeAllItems();
    	cboBox.addItem("------SELECT------");
    	try {
    		ste=con.createStatement();
    		String query="SELECT DISTINCT BusDriverName FROM busdriver ORDER BY BusDriverName";
    		rs=ste.executeQuery(query);
    		
    		while(rs.next()) {
                    if(rs.getString(1).equals("null")){
                        cond=false;
                    }
                    else{
                        cond=true;
                    }
                    if(cond){
                        cboBox.addItem(rs.getString(1));
                    }
    		}
    	}catch(Exception e) {
    		System.out.println(e);
    	}
    }
    
    private void addCboBusLine(JComboBox cboBox) {
    	cboBox.removeAllItems();
    	cboBox.addItem("------SELECT------");
    	try {
    		ste=con.createStatement();
    		String query="SELECT DISTINCT BusLineNo FROM busline ORDER BY BusLineNo";
    		rs=ste.executeQuery(query);
    		
    		while(rs.next()) {
    			cboBox.addItem(rs.getString(1));
    		}
    	}catch(Exception e) {
    		System.out.println(e);
    	}
    }
    
    private String getAutoID(String field, String table, String prefix) {
    	
    	DBConnection connect=new DBConnection();
    	if(table.equals("busdriverdetail")) {
    		return connect.getPrimaryKey2(field, table, prefix);
    	}
    	else if(table.equals("updatedetail")) {
    		return connect.getPrimaryKey3(field, table, prefix);
    	}
    	else {
    		return connect.getPrimaryKey(field, table, prefix);
    	}
    }
    
    public void clearData(){
        CboDriverName.setSelectedIndex(0);
        CboBusLineNo.setSelectedIndex(0);
        txtLisence.setText("");
        Errorlblname.setText("");
        ErrorlblBusLine.setText("");
        ErrorlblLicense.setText("");
        jDateChooser1.setDate(date);
    }
    
  //Function to Add bus route to Database
    private void addUpdateDetail(String description) {    	    	    	       	    	    	
    	
    	try {    		
    		con=new DBConnection().getDBConnection();
    		ste=con.createStatement();
    		int result=0;	    	

    		//Auto ID for updateDetail-id in updateDetail table
    		String updateID=getAutoID("UpdateID", "updatedetail", "U");    		
	    			    			    		
    		String sql="INSERT INTO updatedetail(UpdateID, UserName, Date, Description) VALUES('" + updateID + "', '" + user.getUserName() + "', '" + new UpdateDate().getDate() + "', '" + description + "')";
    		result=ste.executeUpdate(sql);			    				    			    	
	    	   
	    	if(result==1) {
	    		System.out.println("Update Detail: Updated!");
	    	}
    	}catch(Exception e) {
    		System.out.println(e);
    	}    	
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboBusLineNo;
    private javax.swing.JComboBox<String> CboDriverName;
    private javax.swing.JLabel ErrorlblBusLine;
    private javax.swing.JLabel ErrorlblDate;
    private javax.swing.JLabel ErrorlblLicense;
    private javax.swing.JLabel Errorlblname;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtLisence;
    // End of variables declaration//GEN-END:variables
}
